spring:
  profile:
    active: ${ACTIVE_SPRING_PROFILE:test}
  flyway:
    schemas: user
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema?currentSchema=user
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: mappings

