spring:
  profile:
    active: ${prof:test}
  flyway:
    enabled: true
    currentSchema: user
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema?currentSchema=user
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: mappings

